### PR TITLE
Fixes #997 avatar now sets to default values

### LINKED ISSUE #997: Avatar does not reset to default avatar room
## Description

The avatar does not reset to default one with default options (hair, eyes, clothes) in avatar room.
This eventually leads to app crash if the device's screen is turned off. There are errors in writing in database that needs to be handled properly.

## Mocks

videotogif_2018 02 14_12 50 53

### Update 
- [ ] Changes in database

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours 

**I would like to work on the issue**

### PR DESCRIPTION
**Pull request by Rimjhim28**
### Description
Using static variable "hasPreviouslyCustomized", declared in SessionHistory.java with a default value of false to check if the variable was previously customized by the user.
The variable also changes to false whenever the user chooses "NEW GAME" such that the avatar resets to default values.
The if else block in AvatarRoom.java checks is the user has previously changed the default values or not and updates the avatar accordingly. 
Fixes #997 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
The code has been tested on Android Studio emulator.
videotogif_2018 03 18_18 13 10

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@m-murad The PR resets the values as desired. For the crash reported on the issue, I don't think it was due to this issue. I will work on it more and will update you.

File: PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java [hunk 1]
```diff
@@ -77,9 +78,11 @@ public void onClick(DialogInterface dialog, int id) {
                     drawable.setAlpha(200);
                     dialog.getWindow().setBackgroundDrawable(drawable);
                     dialog.show();
+                    SessionHistory.hasPreviouslyCustomized = false;
                 } else{
                     Intent intent = new Intent(getApplicationContext(),AvatarRoomActivity.class);
                     startActivity(intent);
+                    SessionHistory.hasPreviouslyCustomized = false;
```
Comment (Vaibhavi24) [inline PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java]: The statement SessionHistory.hasPreviouslyCustomized = false has been included in both the if block and else block. Why not include this once at the end outside the if-else block?

Comment (asclepiusgal) [reply PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java]: @Rimjhim28 any response to this inquiry?
