### PR TITLE
Fixed the ending case for  save blood

### LINKED ISSUE #1295: Save The Blood mini game is never marked as complete
## Description
As a developer,
I need to handle error with the mini game - Save the blood,
so that the mini game is marked complete once it is played.
Currently, the mini-game is not marked complete. Due to this when the game is completed and another scenario is chosen, the game launches again.

## Mocks
Steps to reproduce:
1. Complete the mini game
2. Go to scenario over screen
3. Click Map to launch map for level 2
4. Click on any scenario
5. The mini game launches again though it was completed

### Update
- [ ] Mark the mini game as completed in Session Manager

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by Rimjhim28**
### Description
The error was in SaveTheBloodEndActivity where the variable OpenedStatus was not reset to false
While fixing this issue, I came across another problem. 
Once all the scenes in Level 2 are played, no matter which scene is chosen for replay, the home scenario was launched always. The problem was in switch case block inside the click listener for replay button. I fixed this as well

Fixes #1295 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Steps to reproduce:
1. Complete the save the blood game
2. Launch map again from the game over screen
3. Choose any scenario to replay
The selected scenario will be replayed whereas initially Save Blood game was always launched.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

File: PowerUp/app/src/main/java/powerup/systers/com/ui/scenario_over_screen_level2/ScenarioOverLevel2Activity.java [hunk 1]
```diff
@@ -124,19 +124,19 @@ public void replayButtonListener (View view) {
             String scenario = getIntent().getStringExtra(PowerUpUtils.SCENARIO_NAME);
             int id;
             switch (scenario) {
-                case "Home":
+                case "Home Level 2":
                     id = 4;
```
Comment (Rimjhim28) [inline PowerUp/app/src/main/java/powerup/systers/com/ui/scenario_over_screen_level2/ScenarioOverLevel2Activity.java]: Fixed the functionality of replay button

File: PowerUp/app/src/main/java/powerup/systers/com/utils/PowerUpUtils.java [hunk 2]
```diff
@@ -59,7 +59,7 @@
             {"Round 3 Pro 1 ", "Round 3 Pro 2", "Round 3 Con 1"}};
     public static final String[][] SWIM_SINK_QUESTION_ANSWERS = {{"Test Ques 1: \n Answer=F", "F"}, {"Test Ques 2: \n Answer=T", "T"}, {"Test Ques 3: \n Answer=T", "T"}, {"Test Ques 4: \n Answer=F", "F"}, {"Test Ques 5: \n Answer=F", "F"}};
     public static final int[] SWIM_TUTS = {R.drawable.swim_tut1, R.drawable.swim_tut2, R.drawable.swim_tut3};
-    public static final int[] SCENARIO_BACKGROUNDS = {R.drawable.background, R.drawable.background, R.drawable.background, R.drawable.home_bg, R.drawable.classroom, R.drawable.hospital_bg, R.drawable.library};
+    public static final int[] SCENARIO_BACKGROUNDS = {R.drawable.background, R.drawable.background, R.drawable.background, R.drawable.home_bg, R.drawable.classroom, R.drawable.hospital_bg, R.drawable.library, R.drawable.home_bg, R.drawable.classroom, R.drawable.hospital_bg, R.drawable.library};
```
Comment (Rimjhim28) [inline PowerUp/app/src/main/java/powerup/systers/com/utils/PowerUpUtils.java]: Duplicated the items keeping in future inclusion of new backgrounds for Level 2
