### PR TITLE
Functionality to the end screen of memory match

### LINKED ISSUE #1212: Add functionality to game completion screen of mini game 2
## Description
As a developer,
I need to add functionality to game completion screen of the mini game 2,
so that score and number of correct and wrong hit are displayed properly.

## Mocks

35922879_1659535490831422_30619689436577792_n

### Update
- [ ] Java file for the functionality
- [ ] All the tests should pass

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

### PR DESCRIPTION
**Pull request by Rimjhim28**
### Description
The code updates the values of score, number of correct answers and number of wrong answers that are passed as intent extras.

Fixes #1212 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by asclepiusgal** [comment]
Okay, will wait to review 13 & 14

File: PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java [hunk 1]
```diff
@@ -113,7 +114,7 @@ public void onClick(DialogInterface dialog, int id) {
         aboutButton.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View view) {
-                startActivity(new Intent(StartActivity.this, AboutActivity.class));
+                startActivity(new Intent(StartActivity.this, MemoryMatchTutorialActivity.class));
                 overridePendingTransition(R.animator.fade_in_custom, R.animator.fade_out_custom);
```
Comment (thisum) [inline PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java]: Seems you're on the test mode here

Comment (Rimjhim28) [reply PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java]: @thisum I will update the PR after #1214 is merged. The duplicate files could be removed only after that.
