### PR TITLE
Fixes #1000 Green tick implementation

### LINKED ISSUE #1000: Green ticks in store not working as expected
## Description

The implementation of green ticks were to show a green tick on items that have been already bought and is set on the avatar. 
Currently, there are several errors on the implementation that needs to be handled like ticks not appearing for the items that are set on avatar, ticks appearing on multiple items, ticks appearing on items that are not selected

## Mocks
No ticks:
no ticks

no tick

Tick on wrong store item:
wrong tick

Appearance of multiple ticks:
mutiple ticks

### Update
- [ ] Rectification to methods in StoreActivity.java

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**I would like to work on the issue**

### PR DESCRIPTION
**Pull request by Rimjhim28**
### Description
A method getselectedItemId() is included in place of variable selectedItemId to correctly identify and distinguish among hair, clothes and accessories and set the ticks accordingly.

Fixes #1000

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

The changes have been tested on Android Studio emulator.
screenshot_2018-04-03-00-08-33-540_powerup systers com powerup

screenshot_2018-04-03-00-07-34-693_powerup systers com powerup

screenshot_2018-04-03-00-07-31-233_powerup systers com powerup

screenshot_2018-04-03-00-07-17-588_powerup systers com powerup

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Rimjhim28** [comment]
@m-murad @saurabhjn76 @niksj Please review.

File: PowerUp/app/src/main/java/powerup/systers/com/StoreActivity.java [hunk 1]
```diff
@@ -427,6 +422,19 @@ public void onClick(DialogInterface dialog, int id) {
...
+            case 0: // hair
+                return getmDbHandler().getAvatarHair();
+            case 1: // clothes
+                return getmDbHandler().getAvatarCloth();
+            case 2: // accessories
+                return getmDbHandler().getAvatarAccessory();
+            default:
+                throw new IllegalArgumentException("Invalid store type index");
+                }
+        }
```
Comment (Dilu9218) [inline PowerUp/app/src/main/java/powerup/systers/com/StoreActivity.java]: `435` and `436` needs to be indented properly.

**Comment by Dilu9218** [comment]
The change is ok, please do the necessary indentation to approve.
